---
# ansible/roles/globalindo-simetrika-website/tasks/main.yml
# This app is static HTML served directly by Nginx.

- name: Sync Globalindo website source code
  ansible.builtin.git:
    repo: 'https://github.com/victorimannuel/globalindo-simetrika-website.git'
    dest: "{{ deploy_dir }}/apps/globalindo-simetrika"
    version: main
    recursive: yes
    force: yes

- name: Ensure correct permissions for static files
  ansible.builtin.file:
    path: "{{ deploy_dir }}/apps/globalindo-simetrika"
    state: directory
    mode: '0755'
    recurse: yes

- name: Install dependencies (npm)
  ansible.builtin.command:
    cmd: npm install
    chdir: "{{ deploy_dir }}/apps/globalindo-simetrika"
  become: false

- name: Build static site
  ansible.builtin.command:
    cmd: npm run build
    chdir: "{{ deploy_dir }}/apps/globalindo-simetrika"
  become: false
