---
# ansible/roles/app-travel-api/tasks/main.yml
- name: Template docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ deploy_dir }}/apps/anugrah-travel-api/docker-compose.yml"
    mode: '0644'

- name: Build and Start API application
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_dir }}/apps/anugrah-travel-api"
    state: present
    build: always
