---
# ansible/playbooks/deploy-apps.yml
- name: Redeploy Applications Only
  hosts: webservers
  vars_files:
    - ../inventories/group_vars/all/vars.yml
    - ../inventories/group_vars/all/vault.yml

  # Infra services are assumed to be already provisioned.
  # Each app role is responsible for syncing only its own source code.
  roles:
    - role: radar-mandiri-sukses-website
      tags: ['rms']

    - role: anugrah-travel-api
      tags: ['travel']

    - role: globalindo-simetrika-website
      tags: ['globalindo']
