server {
  listen 80;
  server_name _;
  # server_name .gs.imannuelvictor.com;

  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name 
    gs.imannuelvictor.com;

  ssl_certificate /etc/nginx/ssl/origin.crt;
  ssl_certificate_key /etc/nginx/ssl/origin.key;

  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers on;

  root /var/www/gs/public;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }
}
