---
# ansible/inventory/group_vars/all/vars.yml
# General Deploy configuration
deploy_dir: /opt/imeco-infra

# These variables define structural paths inside the deploy dir
apps_dir: "{{ deploy_dir }}/apps"
services_dir: "{{ deploy_dir }}/services"
data_dir: "{{ deploy_dir }}/data"

# Local source directory for SSL certificates (OUTSIDE the repo for security)
# This path is relative to the playbooks folder: ../../../ssl
local_ssl_path: "{{ playbook_dir }}/../../../ssl"
